### PR TITLE
Fixes argument passing from CLI to Miner

### LINKED ISSUE #9: undefined method `files' for "[GITHUB_TOKEN]":String
We're passing the token in place of the GithubClient. Oops.

### PR DESCRIPTION
**Pull request by jonnyarnold**
Fixes #9

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
_If you're new, read the [guidelines](https://github.com/reevoo/guidelines/blob/master/pull_requests.md)._

Good code is **tested**, **easy to understand** and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [ ] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [ ] Tests are green on CI (or pulled/tested on your machine).
- [ ] Tests cover happy and unhappy paths in the code.
- [ ] The code is easy to understand.

**Comment by jonnyarnold** [comment]
Sorry Samuel.

**Comment by reevoo-samuel** [comment]
I don't see any comments on your Pull Request.

Are you too good for code reviews now?
No. No you aren't.

Maybe you forgot to say who reviewed it. That's fine, but let me know.

**Comment by Antti** [comment]
Version 1.0.1 already. Is it that stable already?

**Pull request merged**
