### PR TITLE
DRY out miner

### PR DESCRIPTION
**Pull request by lpil**
Nice tool. :)

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
_If you're new, read the [guidelines](https://github.com/reevoo/guidelines/blob/master/pull_requests.md)._

Good code is **tested**, **easy to understand** and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [x] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [x] Tests are green on CI (or pulled/tested on your machine).
- [ ] Tests cover happy and unhappy paths in the code.
- [x] The code is easy to understand.

**Comment by lpil** [comment]
Hi Sammy

**Comment by Antti** [comment]
Looks better, but doesn't solve the problem, where we should bundler to parse gemfile and use Gemspec to access dependencies.

**Comment by lpil** [comment]
Fo sho :+1:

**Comment by jonnyarnold** [comment]
Thanks @lpil :tada: 

@Antti - We're tracking that (#1), but it's quite a big change. We'll sort that for v2 :dancer:

**Comment by jonnyarnold** [comment]
Code Climate is now up to 4.0. Let's try to keep it that way!

**Comment by mikekr1** [comment]
:+1:

**Pull request merged**
